- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/git.yml
    - include: tasks/core-setup.yml
    - include: tasks/zsh.yml
    - include: tasks/ssh.yml
    - include: tasks/nvim.yml
    - include: tasks/dotfiles.yml
    - include: tasks/productivity.yml

